spring:
  application:
    name: jwt-example

  # # Locale
  # web:
  #  locale-resolver: fixed
  #  locale: pt_BR  

  datasource:
    url: jdbc:h2:mem:jwttest
    driverClassName: org.h2.Driver
    username: sa
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  #   show_sql: true
  #   hibernate:
  #     ddl-auto: update
  #   properties:
  #     hibernate:
  #       "[show_sql]": true
  #       "[format_sql]": false
  #   defer-datasource-initialization: true