spring:
  application:
    name: jwt-service

  datasource:
    url: jdbc:postgresql://localhost:5432/parking_api
    username: postgres
    password: 1234
    # driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
# server:
#   port: 8081

jwt:
  secret: "12345678"