spring:
  application:
    name: jwt-example

  # Locale
  web:
   locale-resolver: fixed
   locale: pt_BR  

  datasource:
    url: jdbc:postgresql://localhost:5432/jwt-example
    username: postgres
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        "[show_sql]": true
        "[format_sql]": false
    defer-datasource-initialization: true